package com.aerodrive.api;
import org.springframework.http.ResponseEntity; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api") @CrossOrigin(origins="http://localhost:3000")
public class AircraftController {
  private final List<Aircraft> data = SeedData.all();
  @GetMapping("/aircraft") public List<Aircraft> all(@RequestParam(required=false) String q,@RequestParam(required=false) String category,@RequestParam(required=false) String manufacturer){return data.stream().filter(a->{String hay=(a.name()+" "+a.manufacturer()+" "+a.country()+" "+a.category()+" "+a.role()).toLowerCase();return (q==null||q.isBlank()||hay.contains(q.toLowerCase()))&&(category==null||category.isBlank()||a.category().equalsIgnoreCase(category))&&(manufacturer==null||manufacturer.isBlank()||a.manufacturer().equalsIgnoreCase(manufacturer));}).toList();}
  @GetMapping("/aircraft/{slug}") public ResponseEntity<Aircraft> one(@PathVariable String slug){return data.stream().filter(a->a.slug().equals(slug)).findFirst().map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());}
  @GetMapping("/categories") public Map<String,Long> categories(){return data.stream().collect(java.util.stream.Collectors.groupingBy(Aircraft::category,LinkedHashMap::new,java.util.stream.Collectors.counting()));}
  @GetMapping("/manufacturers") public List<String> manufacturers(){return data.stream().map(Aircraft::manufacturer).distinct().sorted().toList();}
  @GetMapping("/compare") public List<Aircraft> compare(@RequestParam List<String> slugs){return data.stream().filter(a->slugs.contains(a.slug())).toList();}
  @GetMapping("/health") public Map<String,Object> health(){return Map.of("service","aerodrive-api","aircraft",data.size(),"status","ok");}
}
final class SeedData {
  static List<Aircraft> all(){
    return List.of(
      a(1,"boeing-787-dreamliner","Boeing 787 Dreamliner","Boeing","United States","Airliner","2009","A long-range, wide-body twin-engine jet family designed around fuel efficiency, composite structures and passenger comfort.",68.3,60.1,17.0,"Mach 0.90",13620,"2 + cabin crew","2 × high-bypass turbofans","In service","Long-haul passenger transport",13100,List.of("787 program launched in 2003 as Boeing’s new composite wide-body family.","The 787 completed its first flight in December 2009.","Commercial service began with the 787-8 in 2011."),List.of(v("787-8","Original production variant."),v("787-9","Stretched variant with additional capacity and range."),v("787-10","Further-stretched variant optimized for higher capacity routes.")),List.of("Large one-piece composite barrel sections","Advanced wing architecture","Long-range twin-engine layout")),
      a(2,"airbus-a350-900","Airbus A350-900","Airbus","European Union","Airliner","2013","A long-range wide-body twin-engine aircraft with extensive use of advanced materials and a high-composite airframe.",66.8,64.75,17.05,"Mach 0.89",15000,"2 + cabin crew","2 × high-bypass turbofans","In service","Long-haul passenger transport",13100,List.of("The A350 was developed as a new-generation wide-body family.","The A350-900 first flew in June 2013.","It entered airline service in January 2015."),List.of(v("A350-900","Baseline production member."),v("A350-1000","Stretched member with higher passenger capacity.")),List.of("Carbon-fibre reinforced polymer fuselage and wings","High-efficiency twin-engine architecture","Designed for long-range operations")),
      a(3,"f-35a-lightning-ii","F-35A Lightning II","Lockheed Martin","United States","Fighter","2006","A single-seat multirole fighter aircraft developed for air forces and allied operators with low-observable design features.",15.7,10.7,4.38,"Mach 1.6",2200,"1","1 × turbofan","In service","Multirole fighter",15000,List.of("The Joint Strike Fighter program consolidated several national fighter requirements.","The F-35A conventional takeoff variant first flew in December 2006.","The first operational F-35A squadrons were declared later in the program."),List.of(v("F-35A","Conventional takeoff and landing variant."),v("F-35B","Short takeoff and vertical landing variant."),v("F-35C","Carrier-capable variant with larger wing.")),List.of("Sensor fusion architecture","Low-observable shaping","Internal weapons carriage")),
      a(4,"c-17-globemaster-iii","C-17 Globemaster III","Boeing","United States","Military Transport","1991","A strategic airlift aircraft designed for rapid transport of troops and cargo, including operations into austere airfields.",53.0,51.8,16.8,"Mach 0.77",4480,"3","4 × high-bypass turbofans","In service","Strategic / tactical airlift",13700,List.of("The C-17 was developed to replace aging strategic and tactical airlift fleets.","The prototype first flew in September 1991.","Production continued for more than two decades."),List.of(v("C-17A","Primary production and service configuration.")),List.of("Rear loading cargo ramp","Short-field performance","Large strategic airlift capacity")),
      a(5,"rafale","Rafale","Dassault Aviation","France","Fighter","1986","A twin-engine multirole fighter designed for air defence, strike, reconnaissance and carrier operations.",15.3,10.9,5.3,"Mach 1.8",3700,"1–2","2 × turbofans","In service","Multirole fighter",15200,List.of("The Rafale traces its development to French efforts to retain an independent multirole fighter capability.","The Rafale A technology demonstrator first flew in 1986.","Operational variants entered French service during the 2000s."),List.of(v("Rafale C","Single-seat land-based fighter."),v("Rafale B","Two-seat land-based fighter."),v("Rafale M","Carrier-capable naval variant.")),List.of("Delta wing and close-coupled canards","Carrier-capable M variant","Multirole mission set")),
      a(6,"apache-ah-64","AH-64 Apache","Boeing","United States","Helicopter","1975","A two-seat attack helicopter designed for armed reconnaissance, anti-armour missions and close air support.",17.7,14.6,4.0,"~365 km/h",480,"2","2 × turboshafts","In service","Attack helicopter",6400,List.of("The Apache was selected in the 1970s as the U.S. Army’s advanced attack helicopter.","The prototype first flew in September 1975.","Multiple modernized variants have followed since original fielding."),List.of(v("AH-64D","Apache Longbow variant with mast-mounted radar options."),v("AH-64E","Modernized Guardian configuration.")),List.of("Tandem two-seat cockpit","Coaxial weapons / sensor architecture","Designed for low-level armed reconnaissance")),
      a(7,"boeing-747-8","Boeing 747-8","Boeing","United States","Airliner","2010","The latest passenger and freighter generation of the iconic 747 wide-body family.",76.4,68.4,19.4,"Mach 0.855",14815,"2 + cabin crew","4 × high-bypass turbofans","In service / limited production","Large wide-body transport",13100,List.of("The 747 family entered commercial service in 1970.","The 747-8 introduced a stretched fuselage and new-generation engines and wings.","The passenger 747-8I entered service in 2012."),List.of(v("747-8I","Intercontinental passenger variant."),v("747-8F","Freighter with nose cargo door.")),List.of("Distinctive upper-deck profile","747-8F nose cargo access","Four-engine wide-body layout")),
      a(8,"airbus-a320neo","Airbus A320neo","Airbus","European Union","Airliner","2014","A re-engined single-aisle airliner family emphasizing lower fuel burn and improved operating economics.",37.57,35.8,11.76,"Mach 0.82",6300,"2 + cabin crew","2 × high-bypass turbofans","In service","Short / medium-haul passenger transport",11800,List.of("The A320 family entered service in 1988.","The neo program was launched in 2010 with new engines and aerodynamic improvements.","The A320neo entered airline service in 2016."),List.of(v("A319neo","Shorter-fuselage variant."),v("A320neo","Core member of the neo family."),v("A321neo","Stretched variant with higher capacity.")),List.of("Sharklet wingtip devices","New-generation engine options","Single-aisle high-frequency route focus")),
      a(9,"f-22-raptor","F-22 Raptor","Lockheed Martin","United States","Fighter","1997","A twin-engine air-superiority fighter combining low-observable design, high maneuverability and sustained supersonic performance.",18.9,13.6,5.1,"Mach 2.0+",2960,"1","2 × turbofans","In service","Air superiority fighter",19800,List.of("The Advanced Tactical Fighter program led to the YF-22 demonstrator.","The first production-representative F-22 flew in September 1997.","Operational service began in the mid-2000s."),List.of(v("F-22A","Production single-seat fighter.")),List.of("Supercruise capability","Thrust-vectoring control","Internal weapons bays")),
      a(10,"c-130-hercules","C-130 Hercules","Lockheed Martin","United States","Military Transport","1954","A turboprop military transport family known for tactical airlift, special missions and operations from austere runways.",29.8,40.4,11.9,"~671 km/h",3800,"5+","4 × turboprops","In service","Tactical airlift / special missions",10100,List.of("The YC-130 prototype first flew in August 1954.","The Hercules entered service in the 1950s.","The family has evolved through numerous variants and mission kits."),List.of(v("C-130H","Earlier major production generation."),v("C-130J","Modernized Super Hercules generation.")),List.of("Rear loading ramp","Four-engine turboprop","Austere-field operations")),
      a(11,"uh-60-black-hawk","UH-60 Black Hawk","Sikorsky","United States","Helicopter","1974","A medium-lift utility helicopter family designed for troop transport, logistics, evacuation and multiple mission roles.",19.8,16.36,5.13,"~294 km/h",580,"2–4 + passengers","2 × turboshafts","In service","Utility / assault transport",5800,List.of("The U.S. Army selected the S-70 design as the Black Hawk in the 1970s.","The prototype first flew in October 1974.","The UH-60A entered Army service later in the decade."),List.of(v("UH-60A","Original Army utility configuration."),v("UH-60L","Improved engine and systems generation."),v("UH-60M","Modernized digital production generation.")),List.of("Four-blade main rotor","Tactical troop transport role","Highly adaptable mission systems")),
      a(12,"su-57","Su-57","Sukhoi","Russia","Fighter","2010","A twin-engine multirole fighter developed around low-observable features, supermaneuverability and integrated avionics.",19.8,14.1,4.74,"Mach 2.0",3500,"1","2 × turbofans","In service","Multirole fighter",20000,List.of("The PAK FA program targeted a new-generation Russian fighter family.","The first T-50 prototype flew in January 2010.","The Su-57 designation was adopted for the production program."),List.of(v("Su-57","Primary single-seat production fighter.")),List.of("Blended low-observable shaping","High angle-of-attack maneuverability","Internal weapon bays"))
    );
  }
  static Aircraft.Variant v(String n,String notes){return new Aircraft.Variant(n,notes);}
  static Aircraft a(long id,String slug,String name,String manufacturer,String country,String category,String firstFlight,String description,double lengthM,double wingspanM,double heightM,String maxSpeed,int rangeKm,String crew,String engines,String status,String role,int ceilingM,List<String> history,List<Aircraft.Variant> variants,List<String> facts){return new Aircraft(id,slug,name,manufacturer,country,category,firstFlight,description,lengthM,wingspanM,heightM,maxSpeed,rangeKm,crew,engines,status,role,ceilingM,history,variants,facts);}
}
