'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import AircraftCard from './AircraftCard';
import type { Aircraft } from '@/lib/aircraft';
const categories = [{name:'All',icon:'✦'},{name:'Airliner',icon:'✈'},{name:'Fighter',icon:'⚡'},{name:'Military Transport',icon:'▰'},{name:'Helicopter',icon:'◈'}];
export default function Explorer({ aircraft, initialCategory = 'All' }:{aircraft:Aircraft[]; initialCategory?:string}) {
  const [query,setQuery]=useState(''); const [category,setCategory]=useState(initialCategory);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return aircraft.filter(a=>(category==='All'||a.category===category)&&(!q||`${a.name} ${a.manufacturer} ${a.country} ${a.category} ${a.role}`.toLowerCase().includes(q)));},[aircraft,category,query]);
  return <>
    <section className="hero-shell border-b border-white/8"><div className="hero-grid absolute inset-0 opacity-40"/><div className="relative mx-auto max-w-7xl px-6 py-20 sm:py-28"><div className="max-w-5xl"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/8 px-4 py-2 text-[11px] font-bold uppercase tracking-[.22em] text-cyan-200"><span className="h-1.5 w-1.5 rounded-full bg-cyan-300 shadow-[0_0_12px_rgba(103,232,249,.9)]"/>Aircraft knowledge platform</div><h1 className="text-5xl font-semibold tracking-[-.045em] text-white sm:text-7xl">Explore the world of <span className="text-cyan-300">aircraft.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-300 sm:text-lg">A portfolio-ready aircraft encyclopedia with structured specifications, history, comparison tools and interactive 3D exploration.</p><div className="mt-9 flex max-w-3xl items-center rounded-2xl border border-white/10 bg-[#071321]/90 p-2 shadow-2xl shadow-black/20 ring-1 ring-white/5"><span className="px-4 text-slate-500">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} className="min-w-0 flex-1 bg-transparent px-2 py-3 text-sm text-white outline-none placeholder:text-slate-500" placeholder="Search aircraft, manufacturer, country, role..." aria-label="Search aircraft"/>{query&&<button onClick={()=>setQuery('')} className="mr-2 rounded-lg px-3 py-2 text-xs text-slate-400 hover:bg-white/5 hover:text-white">Clear</button>}<button onClick={()=>document.getElementById('library')?.scrollIntoView({behavior:'smooth'})} className="rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950">Search</button></div><div className="mt-5 flex flex-wrap gap-2 text-xs text-slate-400"><span>Try:</span>{['Boeing','Airbus','F-35','Helicopter'].map(term=><button key={term} onClick={()=>setQuery(term)} className="rounded-full border border-white/8 bg-white/4 px-3 py-1.5 hover:border-cyan-300/30 hover:text-cyan-200">{term}</button>)}</div></div></div></section>
    <section id="library" className="mx-auto max-w-7xl px-6 py-12 sm:py-16"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-bold uppercase tracking-[.22em] text-cyan-300">Browse library</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Find an aircraft</h2><p className="mt-2 text-sm text-slate-400">{aircraft.length} curated entries across four aircraft families.</p></div><div className="flex flex-wrap gap-2">{categories.map(c=><button key={c.name} onClick={()=>setCategory(c.name)} className={`rounded-xl border px-4 py-2.5 text-sm transition ${category===c.name?'border-cyan-300/50 bg-cyan-300/10 text-cyan-200':'border-white/8 bg-white/3 text-slate-400 hover:border-white/15 hover:text-white'}`}><span className="mr-2">{c.icon}</span>{c.name}</button>)}</div></div><div className="mt-9 flex items-center justify-between border-b border-white/8 pb-4 text-xs text-slate-500"><span>{filtered.length} result{filtered.length===1?'':'s'}</span><Link href="/compare" className="rounded-full border border-white/8 px-3 py-1.5 text-slate-400 hover:text-white">Open comparison lab →</Link></div>{filtered.length?<div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(a=><AircraftCard key={a.id} a={a}/>)}</div>:<div className="mt-7 rounded-2xl border border-dashed border-white/10 bg-white/2 px-6 py-16 text-center"><div className="text-4xl">⌁</div><h3 className="mt-4 text-lg font-semibold">No aircraft found</h3><p className="mt-2 text-sm text-slate-400">Try a different name, manufacturer or category.</p></div>}</section>
    <section id="about" className="border-t border-white/8 bg-[#060e19]"><div className="mx-auto max-w-7xl px-6 py-14"><div className="grid gap-5 md:grid-cols-4"><div className="rounded-2xl border border-white/8 bg-white/2 p-5"><div className="text-3xl font-semibold">{aircraft.length}</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-slate-500">Aircraft entries</div></div><div className="rounded-2xl border border-white/8 bg-white/2 p-5"><div className="text-3xl font-semibold">4</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-slate-500">Categories</div></div><div className="rounded-2xl border border-white/8 bg-white/2 p-5"><div className="text-3xl font-semibold">3D</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-slate-500">Interactive viewer</div></div><div className="rounded-2xl border border-white/8 bg-white/2 p-5"><div className="text-3xl font-semibold">API</div><div className="mt-2 text-xs uppercase tracking-[.16em] text-slate-500">Spring Boot backend</div></div></div></div></section>
  </>;
}
