export type Variant = { name: string; notes: string };
export type Aircraft = {
  id: number; slug: string; name: string; manufacturer: string; country: string; category: string;
  firstFlight: string; description: string; lengthM: number; wingspanM: number; heightM: number;
  maxSpeed: string; rangeKm: number; crew: string; engines: string; status: string;
  role: string; ceilingM: number; history: string[]; variants: Variant[]; keyFacts: string[];
};

export const aircraftData: Aircraft[] = [
  {id:1,slug:'boeing-787-dreamliner',name:'Boeing 787 Dreamliner',manufacturer:'Boeing',country:'United States',category:'Airliner',firstFlight:'2009',description:'A long-range, wide-body twin-engine jet family designed around fuel efficiency, composite structures and passenger comfort.',lengthM:68.3,wingspanM:60.1,heightM:17.0,maxSpeed:'Mach 0.90',rangeKm:13620,crew:'2 + cabin crew',engines:'2 × high-bypass turbofans',status:'In service',role:'Long-haul passenger transport',ceilingM:13100,history:['787 program launched in 2003 as Boeing’s new composite wide-body family.','The 787 completed its first flight in December 2009.','Commercial service began with the 787-8 in 2011.'],variants:[{name:'787-8',notes:'Original production variant.'},{name:'787-9',notes:'Stretched variant with additional capacity and range.'},{name:'787-10',notes:'Further-stretched variant optimized for higher capacity routes.'}],keyFacts:['Large one-piece composite barrel sections','Advanced wing architecture','Long-range twin-engine layout']},
  {id:2,slug:'airbus-a350-900',name:'Airbus A350-900',manufacturer:'Airbus',country:'European Union',category:'Airliner',firstFlight:'2013',description:'A long-range wide-body twin-engine aircraft with extensive use of advanced materials and a high-composite airframe.',lengthM:66.8,wingspanM:64.75,heightM:17.05,maxSpeed:'Mach 0.89',rangeKm:15000,crew:'2 + cabin crew',engines:'2 × high-bypass turbofans',status:'In service',role:'Long-haul passenger transport',ceilingM:13100,history:['The A350 was developed as a new-generation wide-body family.','The A350-900 first flew in June 2013.','It entered airline service in January 2015.'],variants:[{name:'A350-900',notes:'Baseline production member.'},{name:'A350-1000',notes:'Stretched member with higher passenger capacity.'}],keyFacts:['Carbon-fibre reinforced polymer fuselage and wings','High-efficiency twin-engine architecture','Designed for long-range operations']},
  {id:3,slug:'f-35a-lightning-ii',name:'F-35A Lightning II',manufacturer:'Lockheed Martin',country:'United States',category:'Fighter',firstFlight:'2006',description:'A single-seat multirole fighter aircraft developed for air forces and allied operators with low-observable design features.',lengthM:15.7,wingspanM:10.7,heightM:4.38,maxSpeed:'Mach 1.6',rangeKm:2200,crew:'1',engines:'1 × turbofan',status:'In service',role:'Multirole fighter',ceilingM:15000,history:['The Joint Strike Fighter program consolidated several national fighter requirements.','The F-35A conventional takeoff variant first flew in December 2006.','The first operational F-35A squadrons were declared later in the program.'],variants:[{name:'F-35A',notes:'Conventional takeoff and landing variant.'},{name:'F-35B',notes:'Short takeoff and vertical landing variant.'},{name:'F-35C',notes:'Carrier-capable variant with larger wing.'}],keyFacts:['Sensor fusion architecture','Low-observable shaping','Internal weapons carriage']},
  {id:4,slug:'c-17-globemaster-iii',name:'C-17 Globemaster III',manufacturer:'Boeing',country:'United States',category:'Military Transport',firstFlight:'1991',description:'A strategic airlift aircraft designed for rapid transport of troops and cargo, including operations into austere airfields.',lengthM:53.0,wingspanM:51.8,heightM:16.8,maxSpeed:'Mach 0.77',rangeKm:4480,crew:'3',engines:'4 × high-bypass turbofans',status:'In service',role:'Strategic / tactical airlift',ceilingM:13700,history:['The C-17 was developed to replace aging strategic and tactical airlift fleets.','The prototype first flew in September 1991.','Production continued for more than two decades.'],variants:[{name:'C-17A',notes:'Primary production and service configuration.'}],keyFacts:['Rear loading cargo ramp','Short-field performance','Large strategic airlift capacity']},
  {id:5,slug:'rafale',name:'Rafale',manufacturer:'Dassault Aviation',country:'France',category:'Fighter',firstFlight:'1986',description:'A twin-engine multirole fighter designed for air defence, strike, reconnaissance and carrier operations.',lengthM:15.3,wingspanM:10.9,heightM:5.3,maxSpeed:'Mach 1.8',rangeKm:3700,crew:'1–2',engines:'2 × turbofans',status:'In service',role:'Multirole fighter',ceilingM:15200,history:['The Rafale traces its development to French efforts to retain an independent multirole fighter capability.','The Rafale A technology demonstrator first flew in 1986.','Operational variants entered French service during the 2000s.'],variants:[{name:'Rafale C',notes:'Single-seat land-based fighter.'},{name:'Rafale B',notes:'Two-seat land-based fighter.'},{name:'Rafale M',notes:'Carrier-capable naval variant.'}],keyFacts:['Delta wing and close-coupled canards','Carrier-capable M variant','Multirole mission set']},
  {id:6,slug:'apache-ah-64',name:'AH-64 Apache',manufacturer:'Boeing',country:'United States',category:'Helicopter',firstFlight:'1975',description:'A two-seat attack helicopter designed for armed reconnaissance, anti-armour missions and close air support.',lengthM:17.7,wingspanM:14.6,heightM:4.0,maxSpeed:'~365 km/h',rangeKm:480,crew:'2',engines:'2 × turboshafts',status:'In service',role:'Attack helicopter',ceilingM:6400,history:['The Apache was selected in the 1970s as the U.S. Army’s advanced attack helicopter.','The prototype first flew in September 1975.','Multiple modernized variants have followed since original fielding.'],variants:[{name:'AH-64D',notes:'Apache Longbow variant with mast-mounted radar options.'},{name:'AH-64E',notes:'Modernized Guardian configuration.'}],keyFacts:['Tandem two-seat cockpit','Coaxial weapons / sensor architecture','Designed for low-level armed reconnaissance']},
  {id:7,slug:'boeing-747-8',name:'Boeing 747-8',manufacturer:'Boeing',country:'United States',category:'Airliner',firstFlight:'2010',description:'The latest passenger and freighter generation of the iconic 747 wide-body family.',lengthM:76.4,wingspanM:68.4,heightM:19.4,maxSpeed:'Mach 0.855',rangeKm:14815,crew:'2 + cabin crew',engines:'4 × high-bypass turbofans',status:'In service / limited production',role:'Large wide-body transport',ceilingM:13100,history:['The 747 family entered commercial service in 1970.','The 747-8 introduced a stretched fuselage and new-generation engines and wings.','The passenger 747-8I entered service in 2012.'],variants:[{name:'747-8I',notes:'Intercontinental passenger variant.'},{name:'747-8F',notes:'Freighter with nose cargo door.'}],keyFacts:['Distinctive upper-deck profile','747-8F nose cargo access','Four-engine wide-body layout']},
  {id:8,slug:'airbus-a320neo',name:'Airbus A320neo',manufacturer:'Airbus',country:'European Union',category:'Airliner',firstFlight:'2014',description:'A re-engined single-aisle airliner family emphasizing lower fuel burn and improved operating economics.',lengthM:37.57,wingspanM:35.8,heightM:11.76,maxSpeed:'Mach 0.82',rangeKm:6300,crew:'2 + cabin crew',engines:'2 × high-bypass turbofans',status:'In service',role:'Short / medium-haul passenger transport',ceilingM:11800,history:['The A320 family entered service in 1988.','The neo program was launched in 2010 with new engines and aerodynamic improvements.','The A320neo entered airline service in 2016.'],variants:[{name:'A319neo',notes:'Shorter-fuselage variant.'},{name:'A320neo',notes:'Core member of the neo family.'},{name:'A321neo',notes:'Stretched variant with higher capacity.'}],keyFacts:['Sharklet wingtip devices','New-generation engine options','Single-aisle high-frequency route focus']},
  {id:9,slug:'f-22-raptor',name:'F-22 Raptor',manufacturer:'Lockheed Martin',country:'United States',category:'Fighter',firstFlight:'1997',description:'A twin-engine air-superiority fighter combining low-observable design, high maneuverability and sustained supersonic performance.',lengthM:18.9,wingspanM:13.6,heightM:5.1,maxSpeed:'Mach 2.0+',rangeKm:2960,crew:'1',engines:'2 × turbofans',status:'In service',role:'Air superiority fighter',ceilingM:19800,history:['The Advanced Tactical Fighter program led to the YF-22 demonstrator.','The first production-representative F-22 flew in September 1997.','Operational service began in the mid-2000s.'],variants:[{name:'F-22A',notes:'Production single-seat fighter.'}],keyFacts:['Supercruise capability','Thrust-vectoring control','Internal weapons bays']},
  {id:10,slug:'c-130-hercules',name:'C-130 Hercules',manufacturer:'Lockheed Martin',country:'United States',category:'Military Transport',firstFlight:'1954',description:'A turboprop military transport family known for tactical airlift, special missions and operations from austere runways.',lengthM:29.8,wingspanM:40.4,heightM:11.9,maxSpeed:'~671 km/h',rangeKm:3800,crew:'5+',engines:'4 × turboprops',status:'In service',role:'Tactical airlift / special missions',ceilingM:10100,history:['The YC-130 prototype first flew in August 1954.','The Hercules entered service in the 1950s.','The family has evolved through numerous variants and mission kits.'],variants:[{name:'C-130H',notes:'Earlier major production generation.'},{name:'C-130J',notes:'Modernized Super Hercules generation.'}],keyFacts:['Rear loading ramp','Four-engine turboprop','Austere-field operations']},
  {id:11,slug:'uh-60-black-hawk',name:'UH-60 Black Hawk',manufacturer:'Sikorsky',country:'United States',category:'Helicopter',firstFlight:'1974',description:'A medium-lift utility helicopter family designed for troop transport, logistics, evacuation and multiple mission roles.',lengthM:19.8,wingspanM:16.36,heightM:5.13,maxSpeed:'~294 km/h',rangeKm:580,crew:'2–4 + passengers',engines:'2 × turboshafts',status:'In service',role:'Utility / assault transport',ceilingM:5800,history:['The U.S. Army selected the S-70 design as the Black Hawk in the 1970s.','The prototype first flew in October 1974.','The UH-60A entered Army service later in the decade.'],variants:[{name:'UH-60A',notes:'Original Army utility configuration.'},{name:'UH-60L',notes:'Improved engine and systems generation.'},{name:'UH-60M',notes:'Modernized digital production generation.'}],keyFacts:['Four-blade main rotor','Tactical troop transport role','Highly adaptable mission systems']},
  {id:12,slug:'su-57',name:'Su-57',manufacturer:'Sukhoi',country:'Russia',category:'Fighter',firstFlight:'2010',description:'A twin-engine multirole fighter developed around low-observable features, supermaneuverability and integrated avionics.',lengthM:19.8,wingspanM:14.1,heightM:4.74,maxSpeed:'Mach 2.0',rangeKm:3500,crew:'1',engines:'2 × turbofans',status:'In service',role:'Multirole fighter',ceilingM:20000,history:['The PAK FA program targeted a new-generation Russian fighter family.','The first T-50 prototype flew in January 2010.','The Su-57 designation was adopted for the production program.'],variants:[{name:'Su-57',notes:'Primary single-seat production fighter.'}],keyFacts:['Blended low-observable shaping','High angle-of-attack maneuverability','Internal weapon bays']},
];
